// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:AdministrativeUnit.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// AdministrativeUnit TABLE
class TableAdministrativeUnit extends SqfEntityTableBase {
  TableAdministrativeUnit() {
    // declare properties of EntityTable
    tableName = 'AdministrativeUnit';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.text;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text,
          isUnique: false, isNotNull: false, isIndex: true),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableAdministrativeUnit();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TableAdministrativeUnit.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region AdministrativeUnit
class AdministrativeUnit {
  AdministrativeUnit({this.id, this.name}) {
    _setDefaultValues();
  }
  AdministrativeUnit.withFields(this.id, this.name) {
    _setDefaultValues();
  }
  AdministrativeUnit.withId(this.id, this.name) {
    _setDefaultValues();
  }
  // fromMap v2.0
  AdministrativeUnit.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = o['id'].toString();
    if (o['name'] != null) {
      name = o['name'].toString();
    }

    isSaved = true;
  }
  // FIELDS (AdministrativeUnit)
  String? id;
  String? name;
  bool? isSaved;
  BoolResult? saveResult;
  // end FIELDS (AdministrativeUnit)

  static const bool _softDeleteActivated = false;
  AdministrativeUnitManager? __mnAdministrativeUnit;

  AdministrativeUnitManager get _mnAdministrativeUnit {
    return __mnAdministrativeUnit =
        __mnAdministrativeUnit ?? AdministrativeUnitManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    return map;
  }

  /// This method returns Json String [AdministrativeUnit]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [AdministrativeUnit]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [id, name];
  }

  List<dynamic> toArgsWithIds() {
    return [id, name];
  }

  static Future<List<AdministrativeUnit>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR AdministrativeUnit.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<AdministrativeUnit>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <AdministrativeUnit>[];
    try {
      objList = list
          .map((administrativeunit) => AdministrativeUnit.fromMap(
              administrativeunit as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print(
          'SQFENTITY ERROR AdministrativeUnit.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<AdministrativeUnit>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<AdministrativeUnit> objList = <AdministrativeUnit>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = AdministrativeUnit.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns AdministrativeUnit by ID if exist, otherwise returns null
  ///
  /// Primary Keys: String? id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns AdministrativeUnit if exist, otherwise returns null
  Future<AdministrativeUnit?> getById(String? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    AdministrativeUnit? obj;
    final data = await _mnAdministrativeUnit.getById([id]);
    if (data.length != 0) {
      obj = AdministrativeUnit.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (AdministrativeUnit) object. If the Primary Key (id) field is null, returns Error.
  ///
  /// INSERTS (If not exist) OR REPLACES (If exist) data while Primary Key is not null.
  ///
  /// Call the saveAs() method if you do not want to save it when there is another row with the same id

  /// <returns>Returns BoolResult
  Future<BoolResult> save() async {
    final result = BoolResult(success: false);
    try {
      await _mnAdministrativeUnit.rawInsert(
          'INSERT ${isSaved! ? 'OR REPLACE' : ''} INTO AdministrativeUnit (id,name)  VALUES (?,?)',
          toArgsWithIds());
      result.success = true;
      isSaved = true;
    } catch (e) {
      result.errorMessage = e.toString();
    }

    saveResult = result;
    return result;
  }

  /// saveAll method saves the sent List<AdministrativeUnit> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(
      List<AdministrativeUnit> administrativeunits) async {
    // final results = _mnAdministrativeUnit.saveAll('INSERT OR REPLACE INTO AdministrativeUnit (id,name)  VALUES (?,?)',administrativeunits);
    // return results; removed in sqfentity_gen 1.3.0+6
    await MyDbModel().batchStart();
    for (final obj in administrativeunits) {
      await obj.save();
    }
    //    return MyDbModel().batchCommit();
    final result = await MyDbModel().batchCommit();

    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns 1

  Future<int?> upsert() async {
    try {
      final result = await _mnAdministrativeUnit.rawInsert(
          'INSERT OR REPLACE INTO AdministrativeUnit (id,name)  VALUES (?,?)',
          [id, name]);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'AdministrativeUnit id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'AdministrativeUnit id=$id did not update');
      }
      return 1;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage:
              'AdministrativeUnit Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// Deletes AdministrativeUnit

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted

  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete AdministrativeUnit invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnAdministrativeUnit
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnAdministrativeUnit.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  AdministrativeUnitFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return AdministrativeUnitFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  AdministrativeUnitFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return AdministrativeUnitFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }
  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion administrativeunit

// region AdministrativeUnitField
class AdministrativeUnitField extends SearchCriteria {
  AdministrativeUnitField(this.administrativeunitFB);
  // { param = DbParameter(); }
  DbParameter param = DbParameter();
  String _waitingNot = '';
  AdministrativeUnitFilterBuilder administrativeunitFB;

  AdministrativeUnitField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  AdministrativeUnitFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.EQuals, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.NotEQuals, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.EQualsOrNull, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder isNull() {
    administrativeunitFB._addedBlocks = setCriteria(
        0,
        administrativeunitFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      administrativeunitFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          administrativeunitFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          administrativeunitFB._addedBlocks);
      _waitingNot = '';
      administrativeunitFB
              ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
          administrativeunitFB._addedBlocks.retVal;
    }
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      administrativeunitFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          administrativeunitFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          administrativeunitFB._addedBlocks);
      _waitingNot = '';
      administrativeunitFB
              ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
          administrativeunitFB._addedBlocks.retVal;
      administrativeunitFB
              ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
          administrativeunitFB._addedBlocks.retVal;
    }
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      administrativeunitFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          administrativeunitFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          administrativeunitFB._addedBlocks);
      _waitingNot = '';
      administrativeunitFB
              ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
          administrativeunitFB._addedBlocks.retVal;
    }
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      administrativeunitFB._addedBlocks = setCriteria(
          pFirst,
          administrativeunitFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          administrativeunitFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        administrativeunitFB._addedBlocks = setCriteria(
            pFirst,
            administrativeunitFB.parameters,
            param,
            SqlSyntax.LessThan,
            administrativeunitFB._addedBlocks);
      } else {
        administrativeunitFB._addedBlocks = setCriteria(
            pFirst,
            administrativeunitFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            administrativeunitFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        administrativeunitFB._addedBlocks = setCriteria(
            pLast,
            administrativeunitFB.parameters,
            param,
            SqlSyntax.GreaterThan,
            administrativeunitFB._addedBlocks);
      } else {
        administrativeunitFB._addedBlocks = setCriteria(
            pLast,
            administrativeunitFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            administrativeunitFB._addedBlocks);
      }
    }
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.GreaterThan, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.LessThanOrEquals, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.LessThan, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.LessThan, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    administrativeunitFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.LessThanOrEquals, administrativeunitFB._addedBlocks)
        : setCriteria(pValue, administrativeunitFB.parameters, param,
            SqlSyntax.GreaterThan, administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }

  AdministrativeUnitFilterBuilder inValues(dynamic pValue) {
    administrativeunitFB._addedBlocks = setCriteria(
        pValue,
        administrativeunitFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        administrativeunitFB._addedBlocks);
    _waitingNot = '';
    administrativeunitFB
            ._addedBlocks.needEndBlock![administrativeunitFB._blockIndex] =
        administrativeunitFB._addedBlocks.retVal;
    return administrativeunitFB;
  }
}
// endregion AdministrativeUnitField

// region AdministrativeUnitFilterBuilder
class AdministrativeUnitFilterBuilder extends SearchCriteria {
  AdministrativeUnitFilterBuilder(AdministrativeUnit obj) {
    whereString = '';
    groupByList = <String>[];
    _addedBlocks.needEndBlock!.add(false);
    _addedBlocks.waitingStartBlock!.add(false);
    _obj = obj;
  }
  AddedBlocks _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
  int _blockIndex = 0;
  List<DbParameter> parameters = <DbParameter>[];
  List<String> orderByList = <String>[];
  AdministrativeUnit? _obj;
  QueryParams qparams = QueryParams();
  int _pagesize = 0;
  int _page = 0;

  /// put the sql keyword 'AND'
  AdministrativeUnitFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  AdministrativeUnitFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  AdministrativeUnitFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock!.add(true);
    _addedBlocks.needEndBlock!.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock![_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  AdministrativeUnitFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock![_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  AdministrativeUnitFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  AdministrativeUnitFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  AdministrativeUnitFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock![_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock!.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock!.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  AdministrativeUnitFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  AdministrativeUnitFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  AdministrativeUnitFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  AdministrativeUnitFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  AdministrativeUnitField setField(
      AdministrativeUnitField? field, String colName, DbType dbtype) {
    return AdministrativeUnitField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock![_blockIndex]);
  }

  AdministrativeUnitField? _id;
  AdministrativeUnitField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  AdministrativeUnitField? _name;
  AdministrativeUnitField get name {
    return _name = setField(_name, 'name', DbType.text);
  }

  bool _getIsDeleted = false;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text || param.value[0] is String
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName!)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName!);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value = param.value == null
                  ? null
                  : param.value == true
                      ? 1
                      : 0;
              param.value2 = param.value2 == null
                  ? null
                  : param.value2 == true
                      ? 1
                      : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (AdministrativeUnit._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<AdministrativeUnit> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult(success: false);

    if (AdministrativeUnit._softDeleteActivated && !hardDelete) {
      r = await _obj!._mnAdministrativeUnit
          .updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj!._mnAdministrativeUnit.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from AdministrativeUnit ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj!._mnAdministrativeUnit.updateBatch(qparams, values);
  }

  /// This method always returns AdministrativeUnit Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<AdministrativeUnit>
  Future<AdministrativeUnit?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj!._mnAdministrativeUnit.toList(qparams);
    final data = await objFuture;
    AdministrativeUnit? obj;
    if (data.isNotEmpty) {
      obj = AdministrativeUnit.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [AdministrativeUnit]
  ///
  /// <returns>int
  Future<int> toCount(
      [VoidCallback Function(int c)? administrativeunitCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final administrativeunitsFuture =
        await _obj!._mnAdministrativeUnit.toList(qparams);
    final int count = administrativeunitsFuture[0]['CNT'] as int;
    if (administrativeunitCount != null) {
      administrativeunitCount(count);
    }
    return count;
  }

  /// This method returns List<AdministrativeUnit> [AdministrativeUnit]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<AdministrativeUnit>
  Future<List<AdministrativeUnit>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<AdministrativeUnit> administrativeunitsData =
        await AdministrativeUnit.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return administrativeunitsData;
  }

  /// This method returns Json String [AdministrativeUnit]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [AdministrativeUnit]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [AdministrativeUnit]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj!._mnAdministrativeUnit.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [AdministrativeUnit]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] =
        'SELECT `id` FROM AdministrativeUnit WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<String>.
  /// <returns>List<String>
  Future<List<String>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<String> idData = <String>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj!._mnAdministrativeUnit.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as String);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [AdministrativeUnit]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj!._mnAdministrativeUnit.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await AdministrativeUnit.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    _buildParameters();

    final objectFuture = _obj!._mnAdministrativeUnit.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion AdministrativeUnitFilterBuilder

// region AdministrativeUnitFields
class AdministrativeUnitFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }
}
// endregion AdministrativeUnitFields

//region AdministrativeUnitManager
class AdministrativeUnitManager extends SqfEntityProvider {
  AdministrativeUnitManager()
      : super(MyDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'AdministrativeUnit';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion AdministrativeUnitManager
class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
